name: mardodi_checkin
description: แอปเช็คอินเข้างาน MARDODI (GPS + สแกนใบหน้า)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  geolocator: ^11.0.0
  camera: ^0.10.6
  google_mlkit_face_detection: ^0.11.0
  shared_preferences: ^2.2.3
  flutter_background_service: ^5.0.5
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
